
FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./EasyOCR /app
COPY ./gradio /app/gradio
RUN pip3 install --no-cache-dir -e . "gradio==2.8.10" "fastapi==0.75.0"

WORKDIR /workspace

ENV GRADIO_SERVER_NAME=0.0.0.0
ENV PYTHONUNBUFFERED=1

ENTRYPOINT [ "python" ]

CMD ["/app/gradio/app.py"]

EXPOSE 8501

VOLUME /root/.EasyOCR
