
name: HuggingFace Model Publish commit with branch

on:
  push:
    branches:
      - 'master'
    paths:
      - EasyOCR
      - .github/workflows/hf-model-commit-branch.yml
  workflow_dispatch:
    inputs:
      commit_id:
        description: easyocr commit id(like 'master' 'c4f3cd72')
        required: true
        default: master
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  download-and-push-hf-model:
    name: Download Github Releases and push to HuggingFace
    runs-on: ubuntu-latest

    strategy:
      matrix:
        BRANCH_CHECKOUT:
          - ${{ github.event.inputs.commit_id || 'master' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout commit
        run: |
          cd EasyOCR
          git checkout ${{ matrix.BRANCH_CHECKOUT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pip dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            -e ./EasyOCR
            gradio==2.8.10
            fastapi==0.75.0

      - name: Download models by auto load
        env:
          MODULE_PATH: "./models"
        run: python ./models/download.py

      - name: Install huggingface cli
        uses: BSFishy/pip-action@v1
        with:
          packages: huggingface_hub[cli]
          extra: --user

      - name: Log in to Hugging Face CLI
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Upload models to Hugging Face Models
        run: huggingface-cli upload-large-folder --repo-type model --revision master ${{ secrets.HF_USERNAME }}/easyocr ./models/model

      - name: Log out from Hugging Face CLI
        if: always()
        run: huggingface-cli logout
